### ISSUE TITLE
https://matthew-brett.github.io/curious-git is 404

### ISSUE THREAD

**Issue by yarikoptic** [matthew-brett/curious-git#2]
and all references to curious git seems to lead there... where could we find a rendered version or please fix it up

Hi Matthew! ;)

**Comment by matthew-brett** [comment]
Weird.   I've just pushed up a new version - look ok?
Hi Yarik!

**Comment by yarikoptic** [comment]
yeap, it is there now.

@chrispycheng here is a "good night" (and "become a git guru") read for you: https://matthew-brett.github.io/curious-git/
